In [1]:
import numpy as np

In [3]:
arr = np.array([
    [10,23,56],
    [50,20,340],
    [30,60,89]
])
print(arr)

[[ 10  23  56]
 [ 50  20 340]
 [ 30  60  89]]


In [5]:
arr2 = np.array([
    [21,56,89],
    [29,12,45],
    [56,89,78]
])

In [6]:
print(arr,arr2)

[[ 10  23  56]
 [ 50  20 340]
 [ 30  60  89]] [[21 56 89]
 [29 12 45]
 [56 89 78]]


In [8]:
print(arr+arr2)

[[ 31  79 145]
 [ 79  32 385]
 [ 86 149 167]]


In [9]:
print(arr-arr2)

[[-11 -33 -33]
 [ 21   8 295]
 [-26 -29  11]]


In [11]:
print(arr*arr2)

[[  210  1288  4984]
 [ 1450   240 15300]
 [ 1680  5340  6942]]


In [12]:
print(arr%arr2)

[[10 23 56]
 [21  8 25]
 [30 60 11]]


In [13]:
print(arr.dot(arr2))

[[ 4013  5820  6293]
 [20670 33300 31870]
 [ 7354 10321 12312]]


In [14]:
print(arr.shape)

(3, 3)


In [15]:
print(arr.size)

9


In [16]:
print(arr[1])

[ 50  20 340]


In [18]:
print(arr[1][1:4])

[ 20 340]


In [20]:
print(arr[:,:])

[[ 10  23  56]
 [ 50  20 340]
 [ 30  60  89]]


In [25]:
print(arr[1:2,1:2])

[[20]]


In [30]:
print(arr.ndim)

2
