In [1]:
!pip install numpy

In [4]:
import numpy as np

In [2]:
lst = [1,5,9,6,10]


In [20]:
arra = np.array(lst)
print("Numpy Array: \n{}".format(arra))

Numpy Array: 
[ 1  5  9  6 10]


[ 1  5  9  6 10]


In [7]:
print("Datatype of array's element: {}".format(arra.dtype))

int64


In [8]:
print("Type of array: {}".format(type(arra)))

<class 'numpy.ndarray'>


In [12]:
print("Dimension of array: {}".format(arra.ndim))

1


In [14]:
print("Shape of array: {}".format(arra.shape))

(5,)


In [15]:
print("Size of array: {}".format(arra.size))

5


In [24]:
ones =np.ones((3,5),dtype = int)
print("Ones Array: \n{}".format(ones))
print("\nDimesion of array: {}".format((ones.ndim)))
print("\nShape of array: {}".format((ones.shape)))
print("\nDatatype of array's Element: {}".format((ones.dtype)))
print("\nTypes of array: {}".format(type(ones)))
print("\nElements no in Array: {}".format((ones.size)))

Ones Array: 
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

Dimesion of array: 2

Shape of array: (3, 5)

Datatype of array's Element: int64

Types of array: <class 'numpy.ndarray'>

Elements no in Array: 15


In [25]:
ones = np.zeros((6,7),dtype = float)
print("Ones Array: \n{}".format(ones))
print("\nDimesion of array: {}".format((ones.ndim)))
print("\nShape of array: {}".format((ones.shape)))
print("\nDatatype of array's Element: {}".format((ones.dtype)))
print("\nTypes of array: {}".format(type(ones)))
print("\nElements no in Array: {}".format((ones.size)))

Ones Array: 
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]

Dimesion of array: 2

Shape of array: (6, 7)

Datatype of array's Element: float64

Types of array: <class 'numpy.ndarray'>

Elements no in Array: 42
