In [1]:
import numpy as np

In [12]:
arr = np.array([10,21,23,45])
print(arr)

[10 21 23 45]


In [5]:
arr+=1
print(arr)

[11 22 24 46]


In [7]:
arr-=1
print(arr)

[ 9 20 22 44]


In [13]:
arr=arr*2
print(arr)

[20 42 46 90]


In [14]:
arr = arr%3
print(arr)

[2 0 1 0]


In [15]:
arr = arr**3
print(arr)

[8 0 1 0]


In [16]:
arr = arr/2
print(arr)

[4.  0.  0.5 0. ]


In [18]:
print(arr.max())

4.0


In [19]:
print(arr.min())

0.0


In [21]:
arr = np.array([[10,20,30],
               [20,30,40],
               [50,60,70]])
print(arr)

[[10 20 30]
 [20 30 40]
 [50 60 70]]


In [28]:
res = arr.max(axis = 0)
print(res)
for i in range(len(res)):
  print('Maximum in {} row: {}'.format(i,res[i]))

[50 60 70]
Maximum in 0 row: 50
Maximum in 1 row: 60
Maximum in 2 row: 70


In [29]:
res = arr.max(axis = 1)
print(res)
for i in range(len(res)):
  print('Maximum in {} Coulumn: {}'.format(i,res[i]))

[30 40 70]
Maximum in 0 Coulumn: 30
Maximum in 1 Coulumn: 40
Maximum in 2 Coulumn: 70


In [31]:
res = arr.min(axis = 0)
for i in range(len(res)):
  print('Minimum in {} row: {}'.format(i,res[i]))

Minimum in 0 row: 10
Minimum in 1 row: 20
Minimum in 2 row: 30


In [30]:
res = arr.min(axis = 1)
for i in range(len(res)):
  print('Minimum in {} coulumn: {}'.format(i,res[i]))

Minimum in 0 coulumn: 10
Minimum in 1 coulumn: 20
Minimum in 2 coulumn: 50


In [32]:
print('Sum  of matrix: {} '.format(arr.sum()))

Sum  of matrix: 330 
