In [1]:
arr = [10,15,20,30]

In [2]:
import numpy as np

In [3]:
arra = np.array(arr)

In [4]:
print(arra)

[10 15 20 30]


In [8]:
res = np.random.random((3,3))
print(res)

[[0.70501673 0.52776091 0.15453996]
 [0.64254922 0.18472348 0.36787047]
 [0.90705253 0.25725934 0.45721483]]


In [13]:
print(np.random.random())

0.8883234543010043


In [17]:
res1 = np.arange(10,22,2)
print(res1)

[10 12 14 16 18 20]


In [16]:
res1 =np.linspace(10,20,25)
print(res1)

[10.         10.41666667 10.83333333 11.25       11.66666667 12.08333333
 12.5        12.91666667 13.33333333 13.75       14.16666667 14.58333333
 15.         15.41666667 15.83333333 16.25       16.66666667 17.08333333
 17.5        17.91666667 18.33333333 18.75       19.16666667 19.58333333
 20.        ]


In [20]:
res = np.reshape(res1,(2,3))

print(res)

[[10 12 14]
 [16 18 20]]


In [23]:
res = res.reshape(3,2)
print(res)

[[10 12]
 [14 16]
 [18 20]]


In [25]:
print(res)
res2 = res.flatten()
print(res2)

[[10 12]
 [14 16]
 [18 20]]
[10 12 14 16 18 20]
