In [252]:
import numpy as np
lst = [10,20,30,40]

1. Converting a list into numpy Array

In [253]:
np_array = np.array(lst)
print(type(np_array))

<class 'numpy.ndarray'>


2.Arrange Function

In [254]:
#arr = np.arange(start,end,step up)
arr = np.arange(1,10).reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


3. MutliDimension List

In [255]:
arr = [[10,12,20],
        [15,20,30]]
arr = np.array(arr)
print(arr)

[[10 12 20]
 [15 20 30]]


4. size  Function

In [256]:
print('The size of arr: {}'.format(arr.size))
print('The size of 1st row: {}'.format(arr[1].size))

The size of arr: 6
The size of 1st row: 3


5.Shape Function

In [257]:
print('The shape of arr: {}'.format(arr.shape))

The shape of arr: (2, 3)


6. Dtype Function

In [258]:
print("'The data type of array's element:{}".format(arr.dtype))

'The data type of array's element:int64


7. Ndim Function

In [259]:
print('The dimension of arr: {}'.format(arr.ndim))

The dimension of arr: 2


8. Zeros Function

In [260]:
arr_zero = np.zeros((4,3))
print(arr_zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


9. Ones Function

In [261]:
np_ones  = np.ones((3,3))
print(np_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


10. Eye Function : returns the elements in the form of matrix and diagonal is always 1. and apart from diagonal everything is zeo 

In [262]:
arr_eye = np.eye(5,dtype=int)
print(arr_eye)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


10.Empty Function

In [263]:
arr_empty = np.empty((5,5),dtype=float)
print(arr_empty)

[[5.e-324 0.e+000 0.e+000 0.e+000 0.e+000]
 [0.e+000 5.e-324 0.e+000 0.e+000 0.e+000]
 [0.e+000 0.e+000 5.e-324 0.e+000 0.e+000]
 [0.e+000 0.e+000 0.e+000 5.e-324 0.e+000]
 [0.e+000 0.e+000 0.e+000 0.e+000 5.e-324]]


11. Random Function

In [264]:
arr_random = np.random.rand(3,4)
print(arr_random)

[[0.36165062 0.526111   0.42472996 0.81978073]
 [0.57128475 0.88111074 0.80060352 0.34992523]
 [0.77273869 0.89649666 0.78573034 0.28340737]]


In [265]:
# np.random.randin(start:end:no of element)
arr_randint = np.random.randint(1,10,15)
print(arr_randint)

[6 5 8 2 1 8 5 9 9 5 2 5 1 6 7]


In [266]:
print(np.random.randn(10))

[-1.87120247  0.85779193 -0.93330128  0.26973425 -0.91206319 -0.87171282
 -0.94458939 -0.84984818  0.67813101 -2.07581204]


13. Reshape function

In [267]:
arr = np.arange(10,19).reshape(3,3)
print(arr)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


14. Linspace Function

In [268]:
# np.linspace(start,end,no_of elements,dtype) it generate numbers in sequence of qualy distributed
arr = np.linspace(10,50,100,dtype=int).reshape(10,10)
print(arr)

[[10 10 10 11 11 12 12 12 13 13]
 [14 14 14 15 15 16 16 16 17 17]
 [18 18 18 19 19 20 20 20 21 21]
 [22 22 22 23 23 24 24 24 25 25]
 [26 26 26 27 27 28 28 28 29 29]
 [30 30 31 31 31 32 32 33 33 33]
 [34 34 35 35 35 36 36 37 37 37]
 [38 38 39 39 39 40 40 41 41 41]
 [42 42 43 43 43 44 44 45 45 45]
 [46 46 47 47 47 48 48 49 49 50]]


14. Flatten Function

In [269]:
arr_flatten = arr.flatten()
print(arr_flatten)

[10 10 10 11 11 12 12 12 13 13 14 14 14 15 15 16 16 16 17 17 18 18 18 19
 19 20 20 20 21 21 22 22 22 23 23 24 24 24 25 25 26 26 26 27 27 28 28 28
 29 29 30 30 31 31 31 32 32 33 33 33 34 34 35 35 35 36 36 37 37 37 38 38
 39 39 39 40 40 41 41 41 42 42 43 43 43 44 44 45 45 45 46 46 47 47 47 48
 48 49 49 50]


15. Logspace Function

In [270]:
# it is used to generate log value
arr = np.logspace(2,4,10,base = 2)
print(arr)

[ 4.          4.66611616  5.44316     6.34960421  7.4069977   8.64047791
 10.0793684  11.75787594 13.71590373 16.        ]


16 Copy Function

In [271]:
arr_cp = arr.copy()
print(arr_cp)
print('Method_2'.center(20,'-'))
arr_cp = arr
print(arr_cp)

[ 4.          4.66611616  5.44316     6.34960421  7.4069977   8.64047791
 10.0793684  11.75787594 13.71590373 16.        ]
------Method_2------
[ 4.          4.66611616  5.44316     6.34960421  7.4069977   8.64047791
 10.0793684  11.75787594 13.71590373 16.        ]


17. arr.Max() ,arr.min() ,arr.sum()

In [272]:
print('Maximum of arr:{}'.format(arr.max()))
print('Minimum of arr:{}'.format(arr.min()))
print('Sum of arr:{}'.format(arr.sum()))

Maximum of arr:16.0
Minimum of arr:4.0
Sum of arr:88.05950403932448


18. Seed Function

In [273]:
# it generates and random number but it can be detected
arr = np.random.seed(5)
arr = np.random.randint(1,10,6).reshape(3,2)
print(arr)

[[4 7]
 [7 1]
 [9 5]]


19. Sorting Function

In [274]:
arr = [[10,20,30,40],
       [50,96,45,89],
       [16,45,89,46]]
print(np.sort(arr,axis=1)) # sorting in row
print(np.sort(arr,axis=0)) #sorting in coulumn
print(np.sort(arr,axis=1,kind='mergesort'))
print(np.sort(arr,axis = 1,kind='heapsort'))

[[10 20 30 40]
 [45 50 89 96]
 [16 45 46 89]]
[[10 20 30 40]
 [16 45 45 46]
 [50 96 89 89]]
[[10 20 30 40]
 [45 50 89 96]
 [16 45 46 89]]
[[10 20 30 40]
 [45 50 89 96]
 [16 45 46 89]]


20. Mathematical Operation

a. Addition

In [275]:
arr1 = np.arange(21,39).reshape(6,3)
arr2 = np.arange(3,21).reshape(6,3)
print(arr1+arr2)
print('Method_2'.center(50,'-'))
print(arr1+15)

[[24 26 28]
 [30 32 34]
 [36 38 40]
 [42 44 46]
 [48 50 52]
 [54 56 58]]
---------------------Method_2---------------------
[[36 37 38]
 [39 40 41]
 [42 43 44]
 [45 46 47]
 [48 49 50]
 [51 52 53]]


b. Subtraction

In [276]:
print(arr1-arr2)
print(arr1-15)

[[18 18 18]
 [18 18 18]
 [18 18 18]
 [18 18 18]
 [18 18 18]
 [18 18 18]]
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


c. Multiplication

In [277]:
print(arr1*arr2)
print(arr1*10)

[[ 63  88 115]
 [144 175 208]
 [243 280 319]
 [360 403 448]
 [495 544 595]
 [648 703 760]]
[[210 220 230]
 [240 250 260]
 [270 280 290]
 [300 310 320]
 [330 340 350]
 [360 370 380]]


d. Division

In [278]:
print(arr1/2)
print((arr1*arr2)/arr1)

[[10.5 11.  11.5]
 [12.  12.5 13. ]
 [13.5 14.  14.5]
 [15.  15.5 16. ]
 [16.5 17.  17.5]
 [18.  18.5 19. ]]
[[ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]
 [12. 13. 14.]
 [15. 16. 17.]
 [18. 19. 20.]]


e. Remider(%)

In [279]:
print(arr1%2)

[[1 0 1]
 [0 1 0]
 [1 0 1]
 [0 1 0]
 [1 0 1]
 [0 1 0]]


f. Matrix Multiplication

In [280]:
# dot multiplcication
arr1 = np.arange(10,19).reshape(3,3)
arr2 = np.arange(40,49).reshape(3,3)
print(arr1.dot(arr2))

[[1425 1458 1491]
 [1812 1854 1896]
 [2199 2250 2301]]


g. Power

In [281]:
#arr**exponene
print(arr1**2)

[[100 121 144]
 [169 196 225]
 [256 289 324]]


21. Percentile Function

In [282]:
np.random.seed(3)
arr = np.random.randint(1,10,10)
print(arr)
print(np.sort(arr,kind = 'mergesort'))
print(np.percentile(arr,90))

[9 4 9 9 1 6 4 6 8 7]
[1 4 4 6 6 7 8 9 9 9]
9.0


22. Mean , Variance and standard deviation

In [283]:
print(arr)
print('Mean of arr: {}'.format(arr.mean()))
print('Variance of arr: {}'.format(arr.var()))
print('Standard Deviation: {}'.format(arr.std()))

[9 4 9 9 1 6 4 6 8 7]
Mean of arr: 6.3
Variance of arr: 6.410000000000001
Standard Deviation: 2.5317977802344327


23. Filtering an array

In [284]:
#to replace gretr than 10 in arr
arr[arr>5] =50
print(arr)

[50  4 50 50  1 50  4 50 50 50]


In [285]:
print(arr)
arr_fil = arr[arr>5]
print(arr_fil)

[50  4 50 50  1 50  4 50 50 50]
[50 50 50 50 50 50 50]


24. Transposing an Array : converting row into coulumn and coulumn into row

In [286]:
arr = np.arange(1,10).reshape(3,3)
print(arr)
print('Transpose of Arr: \n{}'.format(arr.T))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose of Arr: 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


25. Where Function

In [287]:
arr = np.random.randint(1,50,9).reshape(3,3)
arr[arr>15] = 50
print(arr)
print('Method_2'.center(50,'-'))
# np.where(condition,relace_value,arr)
print(np.where(arr%2==0,'Even',arr))

[[50 50 50]
 [50 50 15]
 [50 50 50]]
---------------------Method_2---------------------
[['Even' 'Even' 'Even']
 ['Even' 'Even' '15']
 ['Even' 'Even' 'Even']]


26. Merging Arrays

a. concatenate

In [288]:
print(arr1)
print(arr2)
# print('Concatenated Array: {}'.format(np.concatenate(arr1,arr2)))
print('After concatenating coulumn wise:\n')
print(np.concatenate((arr1,arr2),axis = 0))

print('After Concatenating row wise:{}'.format(np.concatenate((arr1,arr2),axis = 1)))

[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[40 41 42]
 [43 44 45]
 [46 47 48]]
After concatenating coulumn wise:

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [40 41 42]
 [43 44 45]
 [46 47 48]]
After Concatenating row wise:[[10 11 12 40 41 42]
 [13 14 15 43 44 45]
 [16 17 18 46 47 48]]


b. vstack and hstack

In [289]:
print(np.vstack((arr1,arr2)))
print(np.hstack((arr1,arr2)))

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [40 41 42]
 [43 44 45]
 [46 47 48]]
[[10 11 12 40 41 42]
 [13 14 15 43 44 45]
 [16 17 18 46 47 48]]


27. Splitting Array

In [290]:
print(arr1)
print(np.vsplit(arr1,3))
print('Horizantialy:{}'.format(np.hsplit(arr,3)))

[[10 11 12]
 [13 14 15]
 [16 17 18]]
[array([[10, 11, 12]]), array([[13, 14, 15]]), array([[16, 17, 18]])]
Horizantialy:[array([[50],
       [50],
       [50]]), array([[50],
       [50],
       [50]]), array([[50],
       [15],
       [50]])]


28. Converting images into numpy array

In [291]:
from matplotlib.image import imread

In [292]:
img = imread('img.jpeg')
print(img.shape)

(1024, 1024, 3)
